version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.6.0
  - dependency-name: timex
    versions:
    - 3.6.3
    - 3.7.3
  - dependency-name: credo
    versions:
    - 1.5.4
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.4.0
    - 1.4.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.23.0
    - 7.24.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.2
    - 5.2.0
    - 5.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.12
    - 7.13.5
    - 7.13.8
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.8.0
  - dependency-name: eslint-plugin-html
    versions:
    - 6.1.2
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: element-ui
    versions:
    - 2.15.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
