version: '3'

services:
  elixir:
    image: ghcr.io/h3poteto/elixir-rust-node:1.10.4-rust1.42-node12-slim-buster
    environment:
      HATENA_CONSUMER_KEY: $HATENA_CONSUMER_KEY
      HATENA_CONSUMER_SECRET: $HATENA_CONSUMER_SECRET
    working_dir: /var/opt/app
    volumes:
      - .:/var/opt/app
    links:
      - postgres:postgres
    ports:
      - "4000:4000"
    command: /bin/bash

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: masuda_stream
    ports:
      - "5432:5432"
    volumes:
      - storage:/var/lib/postgres/data

volumes:
  storage:
