version: '3'

services:
  elixir:
    image: ghcr.io/h3poteto/elixir-rust-node:1.12.3-rust1.58-node16-slim-buster
    user: root
    environment:
      HATENA_CONSUMER_KEY: $HATENA_CONSUMER_KEY
      HATENA_CONSUMER_SECRET: $HATENA_CONSUMER_SECRET
      ROLLBAR_ACCESS_TOKEN: $ROLLBAR_ACCESS_TOKEN
    working_dir: /var/opt/app
    volumes:
      - .:/var/opt/app
      - build:/var/opt/app/_build
      - deps:/var/opt/app/deps
      - node_modules:/var/opt/app/assets/node_modules
    links:
      - postgres:postgres
    ports:
      - "4000:4000"
    command: /bin/bash

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: masuda_stream
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - storage:/var/lib/postgres/data

volumes:
  storage:
  deps:
  build:
  node_modules:
