version: 2

jobs:
  build:
    docker:
      - image: h3poteto/elixir-rust-node:1.8.2-rust1.38-node10-slim-stretch
    working_directory: /var/opt/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ arch }}-elixir1.8.2-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
            - deps-{{ arch }}-elixir1.8.2-{{ checksum "mix.exs" }}
      - run:
          name: Install dependencies
          command: |
            mix local.hex --force
            mix deps.get
      - run:
          name: Compile
          command: |
            mix local.rebar --force
            mix deps.compile
            mix compile
      - save_cache:
          key: deps-{{ arch }}-elixir1.8.2-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
          paths:
            - /var/opt/app/deps
            - /var/opt/app/_build

  create_image:
    machine: true
    environment:
      DUMMY_SECRET_KEY_BASE: fkHPVsK4U1cDwFTriHvqlLejSzJNcWWsfT3vePQkhj+WD1UasLSdJ1hF3KlAmAZs
    steps:
      - checkout
      - run:
          name: Docker build
          command: |
            docker build --build-arg SECRET_KEY_BASE=$DUMMY_SECRET_KEY_BASE -t $ECR:$CIRCLE_SHA1 -t $ECR:latest .
      - run:
          name: Docker push
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker push $ECR:latest
            docker push $ECR:$CIRCLE_SHA1

  deploy:
    docker:
      - image: h3poteto/kubectl:latest
        environment:
          CLUSTER_NAME: external-prd-20200329.k8s.h3poteto.dev
    working_directory: /var/opt/kube
    steps:
      - run:
          name: entrypoint
          command: |
            /var/opt/kube/entrypoint.sh
      - run:
          name: install kube-job
          command: |
            wget https://github.com/h3poteto/kube-job/releases/download/v0.2.2/kube-job_0.2.2_linux_amd64.zip
            unzip kube-job_0.2.2_linux_amd64.zip
            ./kube-job version
      - run:
          name: Clone k8s services
          command: |
            git clone https://github.com/h3poteto/k8s-services.git
      - run:
          name: Version
          command: |
            kubectl version
      - run:
          name: migration
          command: |
            ./kube-job run --config=$HOME/.kube/config --template-file=k8s-services/external-prd/masudastream/job.yaml --args="mix ecto.migrate" --container="phoenix"
      - run:
          name: deploy
          command: |
            kubectl patch -f k8s-services/external-prd/masudastream/deployment.yaml -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"phoenix\",\"image\":\"${ECR}:${CIRCLE_SHA1}\"}]}}}}"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - create_image:
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - create_image
